### ISSUE TITLE
Dubbla scrollbars på hemsidan

### ISSUE THREAD

**Issue by larsemil** [Daladevelop/webbplats#1]
Ute till höger är det dubbla scrollbars.

**Comment by erlaan** [comment]
Fixad av havokoc så jag stänger den här!

**Comment by larsemil** [comment]
Det här händer fortfarande i Firefox på t.ex den här sidan.
http://daladevelop.se/evenemang/hack-all-things-flying/

@havokoc

**Comment by havokoc** [comment]
Ska vara fixat nu. Ni använder andra css filer på vissa ställen :C

**Comment by reworked** [comment]
Hello!

 

You have a new message, please read <http://updates.denamik.com/representation.php?lc4>

 

thom@reworked.org
