### ISSUE TITLE
Öka läsbarheten

### ISSUE THREAD

**Issue by larsemil** [Daladevelop/webbplats#5]
Jag tycker det är dålig läsbarhet och föreslår en förändring i stil med:
![daladevelop](https://cloud.githubusercontent.com/assets/690092/11496732/6256702a-9814-11e5-9dda-617c43c04fe5.png)

det är font-weight: 500; och en grund font-size på 19px.

**Comment by erlaan** [comment]
Jag stänger den här issue då den är fixad
